### ISSUE TITLE
weird problem with dispatchMulti

### ISSUE THREAD

**Issue by cdunn2001** [c-blake/cligen#94] opened 2019-03-23 07:04 UTC
This was working on my Linux machine, but on my Mac there are troubles.

I've rebuilt Nim (at top of `master` branch) and redone `nimble install cligen` into a fresh nimble directory. My program works fine with `dispatch()`, but I have this weird error on Mac with `dispatchMulti()`:
```
Error: execution of an external compiler program 'clang++ -c  -w -std=c++11 -I/Users/cdunn2001/repo/gh/pbbam/.git/PREFIX/include -I/usr/local/Cellar/htslib/1.9/include -I/usr/local/Cellar/xz/5.2.4/include   -I/Users/cdunn2001/repo/gh/Nim/lib -o /Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp.o /Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp' failed with exit code: 1

/Users/cdunn2001/repo/gh/Nim/lib/system/gc_common.nim:358:37: error: redefinition of 'pairs_V9csNKH9cGNJ1NFy9aftrGJlg'
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
/Users/cdunn2001/repo/gh/Nim/lib/system/gc_common.nim:355:37: note: previous definition is here
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
```

**Comment by c-blake** [comment] 2019-03-23 10:53
It looks like Nim is emitting the same C declaration in multiple places.  This is certainly a Nim bug just triggered by `dispatchMulti` - even if only in not rejecting the Nim code.  The Nim compiler should never emit such poorly formed C/C++ as to have multiple defining declaration errors.

It may help to see where those the two places are in the generated C++ by running `nim` with `--lineDir:off`.  You can also just `grep -r "pairs_"` through the generated code directory on both Mac & Linux.  That may be illuminating (assuming your test program can be made to not use any other symbol named `pairs`).

The Linux vs. Mac delta may be a gcc/g++ vs clang/clang++ thing (or not if you use the same version of clang++ in both places).  Your `--verbosity:2` flag should show you the compiler in play on both machines.  

It may also help to clear-out your nim cache before compiling.  It's possible your cache got somehow poisoned on your Mac machine but not on your Linux box.

If you/we wanted to create a meaningful Nim Issue from this, then we should really try to reduce your use case to the minimal one causing trouble, and then try to reduce the `cligen` machinery to the minimal possible.  Narrowing the problem down to the point where it's isolated enough the compiler authors can figure it out can, sometimes, be much more work than finding a workaround.  OTOH, sometimes there is no workaround.

**Comment by cdunn2001** [comment] 2019-03-23 15:11
```
/Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp:521:37: error: redefinition of 'pairs_V9csNKH9cGNJ1NFy9aftrGJlg'
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
/Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp:518:37: note: previous definition is here
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
```
```cpp
 518 tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
 519 NI i_9anLbB4VQWiTN1JjnvHUD2g;
 520 tySequence_sM4lkSb7zS6F7OVMvW9cffQ* sugg_ebtbQutaoOj3J1ikmB8D2A_2;
 521 tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
 522 NI i_9anLbB4VQWiTN1JjnvHUD2g;
 523 STRING_LITERAL(TM_822OlwQdrJrSkbCunu8CXA_3, "good", 4);
```
It's in program initialization. Nim often has problems with macros and optimizations at top-level. I'll stick it in a `main()` proc ... Shoot. That's not an option:
```
/Users/cdunn2001/.nimble/pkgs/cligen-0.9.19/cligen.nim(572, 5) Error: 'from' is only allowed at top level
      from os               import commandLineParams
      ^
```

**Comment by c-blake** [comment] 2019-03-23 15:18
Yeah.  `cligen` generates a parser that needs a variety of things, those needs require imports, and Nim only allows `import` at the top level.  I'm unsure what you wanted to stick in a `main` but cannot.  Only 3 lines apart (518 & 521) is pretty close together on the C++ side.  I'm not sure what to recommend beyond what's been said already.

**Comment by cdunn2001** [comment] 2019-03-23 15:20
I think this relates to the other Issue, with globals:
```
../../bio-nim/cligen/cligen.nim(728, 7) Hint: global variable declared here [GlobalVar]
    var pairs: seq[seq[string]]
        ^
```
I'll try threadvar ...

**Comment by cdunn2001** [comment] 2019-03-23 15:24
Oh, btw, yes, I use `gcc` on Linux and `clang` on Mac.

**Comment by c-blake** [comment] 2019-03-23 15:24
`pairs` really doesn't need to be global.  You can indent those few lines in that `topLevelHelp` template and add a `block` no problem. Nim templates are supposed to be hygienic by default.  So, really that particular `pairs` is not *really* a global and I'd call it a false positive on the warning personally.  That said, I'm happy to do that `block:` change in `cligen.nim` (**if** that fixes your problem).

**Comment by cdunn2001** [comment] 2019-03-23 15:25
Maybe Nim templates are not really hygienic when they are top-level?

**Comment by c-blake** [comment] 2019-03-23 15:28
Possible.  If so, that's a very bad bug which would probably receive high priority from Araq & crew.  Anyway, try the block - should take you like 5 min.  If `block` doesn't create a new scope then it's even worse of a Nim bug, but it could just be some kind of corner-case codegen bug not checking a decl has already been emitted.

**Comment by cdunn2001** [comment] 2019-03-23 15:30
I tried `block` and/or/xor `{.threadvar.}`. No joy. Same error: redefined `pairs...` and `i...`.

However, `threadvar` *did* eliminate the warning for Global `pairs`. Note that `i` is a for-loop variable, so it never had a warning for Global, but it suffers exactly the same problem.

**Comment by cdunn2001** [comment] 2019-03-23 15:35
If this is a Nim bug, I'm not hopeful that Araq can fix this quickly. A quicker solution might be to import everything we need directly into the `cligen` namespace, and then to put `dispatchMulti()` into `main()`. My practice would be to use nothing but "cligen" in `main.nim`, so that's not a problem for me.

**Comment by c-blake** [comment] 2019-03-23 15:36
Huh.  That's a really weird error for a for-loop variable.  That makes me think you should maybe double check if this is a recent bug in Nim.  `cligen` should work on Nim's back to 0.19.2.

**Comment by cdunn2001** [comment] 2019-03-23 15:40
Ok. I'll try nim-0.19.2. I guess I should try to use the nimble compiler-selection, rather than rebuilding myself.

First, I did try moving the imports, but then I hit this:
```nim
../../bio-nim/cligen/cligen.nim(805, 26) Error: index out of bounds
    var cases = multiDef[0][2][^1].add(newNimNode(nnkCaseStmt).add(arg0Id))
                           ^
```

**Comment by c-blake** [comment] 2019-03-23 15:40
I'm not sure I understand your proposal, but one other thing you might be able to try is separate the generation of and calling of the multi-dispatcher. If you compile with `-d:printDispatchMulti` then you will see that one macro doesn't do very much.

**Comment by c-blake** [comment] 2019-03-23 15:43
Anyway, it's not so much as "if it's a Nim bug" - it definitely is.  Nim shouldn't generate illegal C, period (well, without `emit` shenanigans).  Whatever resolution that bug sees might make also make Nim reject some code in `cligen`, though.  So, it could be a double-bug or just a Nim bug.

**Comment by cdunn2001** [comment] 2019-03-23 15:53
> I'm not sure I understand your proposal

```nim
proc main() =
  cligen.dispatchMulti(...)

when isMainModule:
  main()
```
Then, when I get errors in cligen from "imports", I move those imports to the top of `cligen.nim`. I don't understand why that doesn't work, but that's why I posted the error.

I'll try nim-0.19.2, but that's just to learn whether this is a recent bug.

After that, I'll try to "separate the generation of and calling of the multi-dispatcher."

... Well that's weird. I had been at 9c2d419 of **cligen**. When I updated to the tip of `master` (108bf5f), I hit this problem:
```
../../bio-nim/cligen/cligen/argcvt.nim(158, 16) template/generic instantiation from here
../../bio-nim/cligen/cligen/argcvt.nim(146, 31) Error: type mismatch: got <type int>
```
Ever seen that?

**Comment by cdunn2001** [comment] 2019-03-23 15:59
How do we print `$int`? There must be a way.

**Comment by c-blake** [comment] 2019-03-23 16:00
I guess I don't see how that proposal can work, but maybe it's too early in the AM.  `dispatchMulti` is a macro that generates procs in your namespace that get called, and those procs need imported symbols.  We could maybe export a dirty template that did all needed imports for you and then people would have to `import cligen; ...cligen.doImports; ... dispatch`.  That gets a little unweildy.

I've never see your new error but it may be related to `$(typedesc)` moving around from typetraits to system.

**Comment by c-blake** [comment] 2019-03-23 16:03
(Basically, I put a `when NimVersion` guard in there at the top of `cligen/argcvt.nim`, but I've never actually tested the guard against a very old version of Nim.)

**Comment by cdunn2001** [comment] 2019-03-23 16:04
`import cligen` imports all symbols from cligen, right? We just need to import into cligen first, and make those publicly available. I'm pretty sure that's possible.

Anyway, I already gave up on that. I am *not* using `main()`, and I am still on `nim-0.19.4`, not an old version at all. I am now at the tip of cligen `master`.

```
$ nim --version
Nim Compiler Version 0.19.4 [MacOSX: amd64]
Compiled at 2019-02-01
```

**Comment by c-blake** [comment] 2019-03-23 16:04
But I don't think the current `cligen` works on < 0.19.2 anyway, and I *thought* `$(typedesc)` was moved into a no-import-needed situation in 0.19.2, but maybe I'm wrong about that version cutoff.

**Comment by c-blake** [comment] 2019-03-23 16:06
Oh, I see.  `cligen` could maybe `export` all the needed symbols from its internal `import`s.  Yeah, that could maybe work.

**Comment by cdunn2001** [comment] 2019-03-23 16:07
But let's worry about this current bug first. All I did was fast-forward to the tip of `master` in **cligen**.

**Comment by c-blake** [comment] 2019-03-23 16:10
Maybe you can comment out that `when` guard and de-dent the `typetraits` import in `cligen/argcvt.nim`?  I usually work with a day or two old HEAD of Nim and don't check old versions very much.  I did test at some point in the past month or so that Nim-0.19.2 and Nim-0.19.4 worked, though.

**Comment by cdunn2001** [comment] 2019-03-23 16:10
```nim
when NimVersion < "0.19.2":
  from typetraits import `$`  # needed for $T before 0.19.2 when system got it
```
Ok, I see what you're talking about, but apparently we need it again for 0.19.4, maybe?

**Comment by c-blake** [comment] 2019-03-23 16:11
Possibly..I don't think I tested old versions against that `when` guard, some something might be broken or we may need a more complex guard.

**Comment by cdunn2001** [comment] 2019-03-23 16:11
```diff
-when NimVersion < "0.19.2":
+when NimVersion < "0.19.2" or NimVersion >= "0.19.4":
```
That worked. But I'm back to the problem with `pairs`.

**Comment by c-blake** [comment] 2019-03-23 16:14
Ok.  Well, it's a bit more editing work to lift out all those `import`s and do all the `export`s so that `import cligen` pulls in everything the generated procs may need *and* we don't really know if that will resolve your issue.  I do use `dispatchMulti` myself without these problems in, e.g., https://github.com/c-blake/suggest as well as the various `test/` programs. So, there may also be something we could do just in your code.

**Comment by cdunn2001** [comment] 2019-03-23 16:15
I tried exporting *everything*. I still have this:
```nim
../../bio-nim/cligen/cligen.nim(807, 26) Error: index out of bounds
    var cases = multiDef[0][2][^1].add(newNimNode(nnkCaseStmt).add(arg0Id))
                           ^
```
So something else is going on. Any ideas?

**Comment by cdunn2001** [comment] 2019-03-23 16:17
> I do use dispatchMulti myself without these problems

I too was using `dispatchMulti()` on Linux without troubles. We can't be too far from a solution.

**Comment by cdunn2001** [comment] 2019-03-23 16:19
```sh
$ nim --version
Nim Compiler Version 0.19.4 [MacOSX: amd64]

$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
```

**Comment by c-blake** [comment] 2019-03-23 16:21
It seems you're using `nim cpp`.  Have you tried just `nim c` or do you only have clang++ but not clang on your Mac?  Or do you really need `nim cpp`?

**Comment by c-blake** [comment] 2019-03-23 16:22
As to that `multiDef` error - that seems pretty bad.  I'm not sure what's causing it, but it's just AST analysis not some missing `import`/symbol.

**Comment by cdunn2001** [comment] 2019-03-23 16:22
Oh, that's a good idea. I need `cpp`, but I can try `c` as a test.

(I'm also installing nim-0.19.2 ... still compiling ... I'll let you know how that goes.)

**Comment by cdunn2001** [comment] 2019-03-23 16:26
Same problems with nim-0.19.2. (And I actually still needed `$` from `typetraits` too. So I don't know how you were able to avoid that. `-I/Users/cdunn2001/.choosenim/toolchains/nim-0.19.2/lib`. Yeah, I'm definitely using stdlib from 0.19.2.)

**Comment by c-blake** [comment] 2019-03-23 16:27
Maybe if there were something wrong with the `[]` symbol on AST nodes going on with the `import`/`export` from `macros` or wherever that's defined it could explain your `multiDef[]` error, but it sounds like out of bounds is not a type error.

**Comment by c-blake** [comment] 2019-03-23 16:28
Well, we can maybe change that `when` guard to `>0.19.4`.  It was only broken for like a few hours in nim-devel before they fixed it.

**Comment by cdunn2001** [comment] 2019-03-23 16:29
Yep, everything works with `c`. *Everything*! That means:

* `$T` is still only available from `typetraits` for a cpp build, which is a Nim bug.
* There is something wrong with C++ code generation for templates, I guess.

**Comment by c-blake** [comment] 2019-03-23 16:29
I just wanted to remove the need for the import entirely "eventually".

**Comment by c-blake** [comment] 2019-03-23 16:29
Wow.  That's good progress.

**Comment by cdunn2001** [comment] 2019-03-23 16:30
You wanna file the Nim bug, or should I?

**Comment by c-blake** [comment] 2019-03-23 16:30
c++ generation for templates with clang++ backend but not g++ backend, as well.

**Comment by c-blake** [comment] 2019-03-23 16:30
You have the full code base that generates the problem.  So, you should do it.  My knowledge is all 2nd hand.

**Comment by cdunn2001** [comment] 2019-03-23 16:31
I might have to double-check on Linux/gcc. The typetraits problem should not depend on the C++ compiler, so that's suspicious.

**Comment by c-blake** [comment] 2019-03-23 16:32
You might generate the c++ on your Mac and scp it over to the Linux box and see if it compiles on g++ under Linux.  Anyway, I can't play with these sorts of scenarios since I don't have the full code.  I can only make suggestions of things to try.

**Comment by c-blake** [comment] 2019-03-23 16:32
I can fix my `when` guard, though. I'll do that now. :-)

**Comment by cdunn2001** [comment] 2019-03-23 16:39
You'd need to drop the when guard completely. With `nim cpp`, even 0.19.2 fails. I'll mention this in the Nim bug.

**Comment by c-blake** [comment] 2019-03-23 16:43
Ok.  I can do that, too.  Just someday, when the dust is all settled, I should remove the import so that `typetraits` need not `export` that `$` forever.

**Comment by c-blake** [comment] 2019-03-23 16:46
Done.  Just always does the `import` from `typetraits` again.  Araq's comment on that was to keep it in `typetraits` forever more anyway.  So, I was probably being too fastidious.

**Comment by cdunn2001** [comment] 2019-03-23 16:52
https://github.com/nim-lang/Nim/issues/10898

**Comment by c-blake** [comment] 2019-03-23 17:29
Cool.  I'm going to close this issue here, then.  I may do that `export` work in the near future (independent, though that is, of getting your stuff to actually work).

**Closed by c-blake** 2019-03-23 17:29 UTC

**Comment by pb-cdunn** [comment] 2019-03-23 18:54
You might want to add yourself to https://github.com/nim-lang/Nim/issues/10898 as I'm learning interesting things.

**Comment by c-blake** [comment] 2019-03-23 19:20
I'm reading along.  It sounds like with nim-devel#HEAD and cligen#HEAD on your Mac you are back to things working.  So, at least you aren't "stopped" anymore.

I was going to punch another release soon and would be fine synchronizing such with a Nim one.  The Nim guys may not be so ready, though.  I think they want this next one to be something like the one before 0.20 and 0.20 to be the one before 1.0 or something like that, and a lot of work on memory management with destructors and all that jazz.  To paraphrase the expression, bigger fish are being fryed than some random bug.

**Comment by cdunn2001** [comment] 2019-03-23 19:37
Well, there is no work-around. And it's not the first time I've been dead-in-the-water with an official release. But yeah, I won't criticize people on an open-source project. I just want people to be aware of the situation.

**Comment by c-blake** [comment] 2019-03-24 11:03
Some might say working off of #HEAD is a "work-around". ;-) But I hear you. There's no question the Nim experience can be rough/is not to be ridden without a helmet. :-(

**Comment by pb-cdunn** [comment] 2019-03-26 18:31
I work in a company. It's not easy getting permission to use Nim at all. When I have to tell people, "Well, the official release is broken, but HEAD seems to work," people lose faith. And this is not the first time.

I only wish the nim-team were more willing to cut a release when they learn the previous one is actually broken. For a long time, the official release had a completely broken memory-manager (for large memory and multiprocessing), but still no interest in cutting a release. And it's not realistic to try to get **nim** into **Bioconda** until it's "stable".

Anyway, I really appreciate your quick responses. And honestly, this is a really great way to write quick command-line tools in *any* language. For now, I'm using Nim to wrap C++ because it's much harder to find/install/configure useful C++ libraries. At my company, I am not even allowed to use `boost::filesystem`, but Nim has a *huge* standard library.

**Comment by c-blake** [comment] 2019-03-26 19:36
I also think it would be better for them to have lots of little "point" releases.  I'm happy to punch one out for `cligen` if that would help you anytime you want.  Just let me know.  I'm not in charge of the main compiler, though, and I doubt they'd listen to me.

Also, while there are always the issues one hits personally, I think there are a large number of very bad bugs in all point Nim releases.  I have a couple very bad outstanding ones going back to last July & November. It can be hard to know which pile of bugs to stamp as more stable than the last.  More point releases helps in situations like this one, though.  Less bugs would be even better than more points. :-)  Nim core really does work with you if you isolate the bug enough that solutions are obvious and/or you propose some PRs, though.  Less so about point releases.  I honestly think they get more hung up on numbers like 1.0 than they should.  The mountain of bugs does make it hard to vigorously recommend to my more timid friends, and yeah companies with broader concerns generally have good reason to be timid.

Anyway, I'm glad you like `cligen`.  I used to use `argh` in my more Pythonic days.  Pretty much as soon as Araq added `getImpl` I did `cligen`.  A few people asked for a lot of features, but it mostly hasn't been too much work to keep its trains running, and now I think `cligen` is quite a bit nicer than `argh`.  I'm unaware of any other such inferred CLI packages, but *many* languages (even C++) have name=value default arguments.  Once your functions can do that, `argh`/`cligen` seems the right way to go - or maybe `docopt` if you are less lazy about documentation and less lazy about learning APIs.  Of course, with C++ you'd need a parser library to do `argh`/`cligen`-style stuff, but people do do all kinds of kooky shenanigans in that world.

Except for maybe a little more message-to-user templating, `cligen` now seems pretty close to feature complete to me.  I also enjoy that Nim is pretty batteries included.  One idea I had might be to do `gdb`/`mercurial`/`gnuplot`-like "shortest identifying prefix" matching on idents like long options or subcommands.  Nim stdlib just has `critbits` which makes it trivial to do efficiently (not that there are ever more than dozens of idents).  I'm not sure how well it would interact with spelling suggestions, though.  That might make more sense as a CLI-author option than being always-on..How much you want "do what I mean" semantics in there sorta depends on how "persistently impactful" running a command may be, though mercurial has a lot of impactful commands.  Might go against least-surprise too much, too.

**Comment by pb-cdunn** [comment] 2019-03-27 15:12
Oh, Nim-devs are great about bug-fixes. They're amazingly quick and thorough.

If I were working independently, I wouldn't complain at all. I can work off `devel`. But I have constraints from my company.

I love Araq's ideas on "owned refs". I hope that gets in soon. It really could simplify a lot of other things.

**Comment by c-blake** [comment] 2019-05-10 20:42
By the way, with my current `cligen` version, I was able to reproduce your error on nim-0.19.2 and nim-0.19.4 with "nim cpp" mode and `test/FullyAutoMulti.nim` - reproduced the C++ compile error even with the `from typetraits import`.  So, I don't think that `import` was specifically triggering the situation "all the time", though it may have been for your code in that version of `cligen`.

However, in *both* those old releases, `test/SubScope.nim` worked for me - compiled and seemed to run fine with just `import typetraits` even.  So, that subscoping which used to not be an option is viable now that `cligen` exports everything generated code needs.  Perhaps this `test/SubScope.nim` approach helps you not be dead in the water in earlier Nim releases (unless you've figured some other way out of that).

Right now that `from import` line does not seem to alter the broken behavior of 0.19.2 or 0.19.4 for me.  It just always breaks with that same `pairs` re-definition type error.  In light of this I am leaning toward changing the line to `from typetraits import` to just `import typetraits` with a comment for eventually resuscitating the `when` guard and then eventually removing.

**Comment by c-blake** [comment] 2019-05-12 13:37
Actually, it turned out that `topLevelHelp` could just move from `template` to `proc` to fix your nim cpp compile errors and we can move the `when` guard to 0.19.4 for the `$` not in system for cpp before post 0.19.4.
