### ISSUE TITLE
Nested usage definition raises ValueError. $subcmds variable is missing

### ISSUE THREAD

**Issue by wulfmann** [c-blake/cligen#129] opened 2020-01-09 16:09 UTC
I would like to be able to specify a usage string for a nested (multi) command.

This file works:

```nim
# replicate.nim
proc child_one(): string = "child one"
proc child_two(): string = "child two"

when isMainModule:
    import cligen

    # Parent One
    dispatchMultiGen(
        ["one"],
        [
            child_one,
            cmdName="child",
            mergeNames = @["one child"],
            dispatchName = "dispatchOneChild"
        ]
    )

    # Parent Two
    dispatchMultiGen(
        ["two"],
        [
            child_two,
            cmdName="child",
            mergeNames = @["two child"],
            dispatchName = "dispatchTwoChild"
        ]
    )

    dispatchMulti(
        ["multi", usage = clUseMultiPerlish],
        [
            one,
            stopWords = @["child"],
            suppress = @["usage", "prefix"]
        ],
        [
            two,
            stopWords = @["child"],
            suppress = @["usage", "prefix"]
        ]
    )
```

Compile:

```bash
nim c -r -d:ssl replicate.nim -h
```

Output:

```bash
NAME
  USAGE
  replicate {SUBCMD}  [sub-command options & parameters]

SUBCOMMANDS
  help  print comprehensive or per-cmd help
  one
  two

replicate {-h|--help} or with no args at all prints this message.
replicate --help-syntax gives general cligen syntax help.
Run "replicate {help SUBCMD|SUBCMD --help}" to see help for just SUBCMD.
Run "replicate help" to get *comprehensive* help.
```

If I want to get the same usage string on a nested subcommand though, an exception is raised:

```nim
# replicate.nim
proc child_one(): string = "child one"
proc child_two(): string = "child two"

when isMainModule:
    import cligen

    # Parent One
    dispatchMultiGen(
        ["one"],
        [
            child_one,
            cmdName="child",
            mergeNames = @["one child"],
            dispatchName = "dispatchOneChild"
        ]
    )

    # Parent Two
    dispatchMultiGen(
        ["two"],
        [
            child_two,
            cmdName="child",
            mergeNames = @["two child"],
            dispatchName = "dispatchTwoChild"
        ]
    )

    dispatchMulti(
        ["multi", usage = clUseMultiPerlish],
        [
            one,
            usage = clUseMultiPerlish, # usage added here
            stopWords = @["child"],
            suppress = @["usage", "prefix"]
        ],
        [
            two,
            stopWords = @["child"],
            suppress = @["usage", "prefix"]
        ]
    )
```

Compile:

```bash
nim c -r -d:ssl replicate.nim one -h
```

Output:

```bash
/.nimble/pkgs/cligen-0.9.41/cligen.nim(920) replicate
/.nimble/pkgs/cligen-0.9.41/cligen.nim(584) multiSubs
/.nimble/pkgs/cligen-0.9.41/cligen.nim(664) multi
/.nimble/pkgs/cligen-0.9.41/cligen.nim(420) dispatchone
/usr/local/Cellar/nim/1.0.4/nim/lib/pure/strutils.nim(2745) %
/usr/local/Cellar/nim/1.0.4/nim/lib/pure/strutils.nim(2691) addf
/usr/local/Cellar/nim/1.0.4/nim/lib/pure/strutils.nim(2634) invalidFormatString
Error: unhandled exception: invalid format string [ValueError]
Error: execution of an external program failed: 'replicate one -h'
```

This is basically what I would like to see when seeing the output of `replicate one -h`:

```bash
Usage:
  replicate {SUBCMD}  [sub-command options & parameters]
where {SUBCMD} is one of:
  help   print comprehensive or per-cmd help
  child

replicate {-h|--help} or with no args at all prints this message.
replicate --help-syntax gives general cligen syntax help.
Run "replicate {help SUBCMD|SUBCMD --help}" to see help for just SUBCMD.
Run "replicate help" to get *comprehensive* help.
```

Am I doing something wrong in my definition here?

I came across this issue that seems related: #107 But I was unable to get my example to work from the information listed there.

Thank you in advance! Let me know if you'd like any more information.

**Comment by wulfmann** [comment] 2020-01-09 16:12
I want to mention that I do see how the fact that the `$subcmd` variable is not getting interpolated for some reason, but I was not able to figure out why that is. I am still getting my feet wet with nim so I apologize in advance if this is obvious!

**Comment by wulfmann** [comment] 2020-01-09 16:19
Finally I should mention that running:

```bash
replicate one
```

without any arguments prints exactly what i'm looking for:

```bash
Usage:
  replicate {SUBCMD}  [sub-command options & parameters]
where {SUBCMD} is one of:
  help   print comprehensive or per-cmd help
  child

replicate {-h|--help} or with no args at all prints this message.
replicate --help-syntax gives general cligen syntax help.
Run "replicate {help SUBCMD|SUBCMD --help}" to see help for just SUBCMD.
Run "replicate help" to get *comprehensive* help.
```

**Comment by c-blake** [comment] 2020-01-09 16:21
Ok.  This seems like plenty of information.  Let me try to compile your examples and reproduce/provide advice/fixes.

**Comment by c-blake** [comment] 2020-01-09 16:48
So, I think the problem/solution is that you are using a ``dispatchMulti`` usage string with the subcommands but in the context of a regular ``dispatch`` parameter list.  (The sub-lists in those inner brackets are just ``dispatch`` parameters.)  I did try to "advertise" this by having "Multi" be part of the name for that convenience format string ``clUseMultiPerlish``, and indeed it does have to do with ``subcommands`` being there.  Put another way, your child one has no subcommands.  So, there would be nothing for that to expand to.

It sounds like you want to just define your own ``clUsePerlish`` (without the Multi or subcommands in the string).  I don't have a ``clUsePerlish`` in ``cligen/helpTmpl.nim`` at present, but I am happy to accept some pull request adding that if you (maybe in collaboration with @kaushalmodi) come up with one.

**Comment by c-blake** [comment] 2020-01-09 16:53
Or maybe really `clUsagePerlish` since it is for a "leaf".  That seems to be my naming convention in `cligen/helpTmpl.nim`.

Anyway, that parameter at the level can only use `$command`, `$args`, `$doc`, or `$options`.  To me this feels like user error/maybe bad documentation.  So, I am closing out the issue, but you can ask questions here if you need to.

**Closed by c-blake** 2020-01-09 16:53 UTC

**Comment by wulfmann** [comment] 2020-01-09 17:04
Thank you for the clarification!

This indeed is a misunderstanding on my part.

I'm not against defining my own usage string, but I don't think I can get the information I want to from any of these:`$command, $args, $doc, or $options`.

When running the command without arguments, this is outputted:

```bash
Usage:
  replicate {SUBCMD}  [sub-command options & parameters]
where {SUBCMD} is one of:
  help   print comprehensive or per-cmd help
  child
...
```

Do you know how I would access those values? (The ones under where {SUBCMD}

**Comment by c-blake** [comment] 2020-01-09 17:20
Well, I don't think you can from within the sub-sub command.  I think that's kind of a violation of the modularity of things/the way I implement `dispatchMulti`.  What I do in my `test/MultiMulti.nim` is just provide a `$doc` via `doc` that directs the wayward user how to get the help you think they want.  That's probably the easiest workaround.

**Comment by wulfmann** [comment] 2020-01-09 17:36
Thanks for all your help!

**Comment by c-blake** [comment] 2020-01-09 17:41
You are welcome!  I hope you enjoy `cligen` and Nim more generally.

Incidentally, the tree structure you were building up made me think that you might also consider looking through the commentary for this issue: https://github.com/c-blake/cligen/issues/113 .

Honestly, 3 levels (master, sub-sub, leaf) already seems like a lot of complexity for end users.  I get the kind of "purity/generality" of N levels.  I also don't think there is a whole lot of established guidance about what help should be dumped where from the larger world of CLI toolkits.

It always has been and probably always will be true that at _some_ amount of CLI author help-pickiness, `cligen` will not be enough.  I do try to provide a lot of hooks & knobs where it's easy, though.  Let me know if you need any more help.  The `test/` programs really are the best starting point.
